inputs:
  gtoken:
    description: 'github token'
    required: true
  chromatic:
    description: 'chromatc token'
    required: true
  NEXT_PUBLIC_API_KEY:
    description: 'env'
    required: true
  NEXT_PUBLIC_APP_ID:
    description: 'env'
    required: true
  NEXT_PUBLIC_AUTH_DOMAIN:
    description: 'env'
    required: true
  NEXT_PUBLIC_MESSAGING_SENDER_ID:
    description: 'env'
    required: true
  NEXT_PUBLIC_PROJECT_ID:
    description: 'env'
    required: true
  NEXT_PUBLIC_STORAGE_BUCKET:
    description: 'env'
    required: true
runs:
  using: 'Composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: install dependency
      run: npm ci -w web
      shell: bash

    - name: storybook test
      env:
        STORYBOOK_NEXT_PUBLIC_API_KEY: ${{ inputs.NEXT_PUBLIC_API_KEY }}
        STORYBOOK_NEXT_PUBLIC_APP_ID: ${{ inputs.NEXT_PUBLIC_APP_ID }}
        STORYBOOK_NEXT_PUBLIC_AUTH_DOMAIN: ${{ inputs.NEXT_PUBLIC_AUTH_DOMAIN }}
        STORYBOOK_NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{ inputs.NEXT_PUBLIC_MESSAGING_SENDER_ID }}
        STORYBOOK_NEXT_PUBLIC_PROJECT_ID: ${{ inputs.NEXT_PUBLIC_PROJECT_ID }}
        STORYBOOK_NEXT_PUBLIC_STORAGE_BUCKET: ${{ inputs.NEXT_PUBLIC_STORAGE_BUCKET }}
      run: npm run test-storybook:ci -w web
      shell: bash

    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ inputs.gtoken }}
        projectToken: ${{ inputs.chromatic }}
        workingDir: ./web
      env:
        STORYBOOK_NEXT_PUBLIC_API_KEY: ${{ inputs.NEXT_PUBLIC_API_KEY }}
        STORYBOOK_NEXT_PUBLIC_APP_ID: ${{ inputs.NEXT_PUBLIC_APP_ID }}
        STORYBOOK_NEXT_PUBLIC_AUTH_DOMAIN: ${{ inputs.NEXT_PUBLIC_AUTH_DOMAIN }}
        STORYBOOK_NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{ inputs.NEXT_PUBLIC_MESSAGING_SENDER_ID }}
        STORYBOOK_NEXT_PUBLIC_PROJECT_ID: ${{ inputs.NEXT_PUBLIC_PROJECT_ID }}
        STORYBOOK_NEXT_PUBLIC_STORAGE_BUCKET: ${{ inputs.NEXT_PUBLIC_STORAGE_BUCKET }}
