inputs:
  secrets:
    description: 'secrets'
    required: true
runs:
  using: 'Composite'
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: install dependency
      run: npm ci -w web
      shell: bash

    - name: storybook test
      run: npm run test-storybook:ci -w web
      shell: bash

    - name: Publish to Chromatic
      uses: chromaui/action@v1
      with:
        token: ${{ inputs.secrets.G_TOKEN }}
        projectToken: ${{ inputs.secrets.CHROMATIC_PROJECT_TOKEN }}
        workingDir: ./web
