import type { NextPage } from 'next'
import Head from 'next/head'
import { login, logout } from 'src/firebase/common'
import { Button } from '@/atoms/Button/Button'
import { useShopQuery } from '@/graphql/generated'

const Home: NextPage = () => {
  const { loading, error, data } = useShopQuery({
    variables: { shopId: 'QCv5QIAxDue0QuirDyoC' },
  })
  const onClickHandler = () => {
    console.log(data)
  }
  const loginHandler = () => {
    login()
  }
  const logoutHandler = () => {
    logout()
  }
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button onClick={onClickHandler}>hoge</Button>
      <Button onClick={loginHandler}>login</Button>
      <Button onClick={logoutHandler}>logount</Button>
    </div>
  )
}

export default Home
