name: Chromatic_onpush

on:
  pull_request:
    paths:
      - 'web/**'

jobs:
  chromatic_onpush:
    if: (github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name , 'renovate'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: storybook test
        uses: .github/actions/storybook
