name: Chromatic
on:
  pull_request:
    paths:
      - 'apps/web/**'

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      # - run: npm ci
      - run: cd apps/web
      - run: npm ci
      - run: npm run chromatic
