name: Chromatic_onready

on:
  pull_request:
    paths:
      - 'web/**'
    types: [ready_for_review]

jobs:
  chromatic_onready:
    if: (github.event.pull_request.draft == false && !contains(github.event.pull_request.labels.*.name , 'renovate'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: storybook test
        uses: ./.github/actions/storybook
        with:
          gtoken: ${{ secrets.G_TOKEN }}
          chromatic: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
