name: Storybook_interaction

on:
  pull_request:
    paths:
      - 'web/**'

jobs:
  nextjs_jest:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Interaction Test
        run: |
          npm ci -w web
          npm run test-storybook:ci -w web
