name: Jest
on:
  pull_request:
    paths:
      - 'web/**'

jobs:
  if: github.event.pull_request.draft == false
  nextjs_jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Unit Test
        run: |
          npm ci -w web
          npm run test -w web
