name: Next.js Test
on:
  pull_request:
    paths:
      - 'apps/web/**'

jobs:
  nextjs_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Unit Test
        working-directory: ./apps/web
        run: |
          npm ci
          npm run test
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.G_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: ./apps/web
