name: next_build

on:
  push:
    paths:
      - 'web/**'

jobs:
  next_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: install dependency
        run: npm ci
      - name: next build
        run: npm run build -w web
